###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "username": "user",
    "password": "123",
    "firstName": "fname",
    "lastName": "lname",
    "gender": "m"
}


###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username": "roni",
    "password": "123"
}


###
POST http://localhost:5000/api/user/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzc3NTExMywianRpIjoiODg5Y2EyMDYtMTgwYi00ZDdmLTllMWQtZDdlYWExNmQ4NDBmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDc3NzUxMTMsImV4cCI6MTcwNzc3ODcxM30.FCiPk4SafzzK-N4HYNHXqy1QAmvM7qZX2fi3K4djrm4

###
POST http://localhost:5000/api/user/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzA4MTI1MCwianRpIjoiZjE2NmVmNTgtNjZiNS00ZGQ0LWFhMmUtYjczYzQ3ZjZjYzkyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InVzZXIiLCJuYmYiOjE3MDcwODEyNTAsImV4cCI6MTcwNzA4MjE1MH0.lOHUEwETaiTIaCq1RD5LDHigrqPa11HfoTAyssvT3E8

###
GET http://localhost:5000/api/user/scores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzA4NDQ3MiwianRpIjoiNDI2YWM2ODUtMmZjYy00YzhlLTlmN2YtNTdhYWYwYThiYWZhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDcwODQ0NzIsImV4cCI6MTcwNzA4NTM3Mn0.CDlOyiLwZzae54ZC3xN_Ei-jVySC6EurP6AZoURqI2E

###
GET http://localhost:5000/api/user/above_average
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzc3NTExMywianRpIjoiODg5Y2EyMDYtMTgwYi00ZDdmLTllMWQtZDdlYWExNmQ4NDBmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDc3NzUxMTMsImV4cCI6MTcwNzc3ODcxM30.FCiPk4SafzzK-N4HYNHXqy1QAmvM7qZX2fi3K4djrm4

###
GET http://localhost:5000/api/artworks/learned
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzc3NTExMywianRpIjoiODg5Y2EyMDYtMTgwYi00ZDdmLTllMWQtZDdlYWExNmQ4NDBmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDc3NzUxMTMsImV4cCI6MTcwNzc3ODcxM30.FCiPk4SafzzK-N4HYNHXqy1QAmvM7qZX2fi3K4djrm4

###
GET http://localhost:5000/api/artworks/filters
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzY3MTk3NywianRpIjoiYjFkZjk3OGEtYTNlYy00ZTg4LWEzMDctMGE4ZGQ0NGMyY2ZhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDc2NzE5NzcsImV4cCI6MTcwNzY3Mjg3N30.eO18WIbuXKPAiVTg_lRB15u6Cp1wEEn0saoU8w_qymk

###
POST http://localhost:5000/api/artworks/filter_results
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzc3NTExMywianRpIjoiODg5Y2EyMDYtMTgwYi00ZDdmLTllMWQtZDdlYWExNmQ4NDBmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDc3NzUxMTMsImV4cCI6MTcwNzc3ODcxM30.FCiPk4SafzzK-N4HYNHXqy1QAmvM7qZX2fi3K4djrm4

{
    "artist_names": ["Pietro Santi Bartoli"],
    "artist_nationalities": [],
    "artwork_culture": [],
    "artwork_classification": [],
    "artwork_period": [],
    "artwork_medium": [],
    "get_oldest_artworks": true,
    "get_different_countries": true
}

###
POST http://localhost:5000/api/artworks/update_test_results
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzc3NDA2OSwianRpIjoiZmM0NjY3MTQtYzVjMy00MzhiLWI4ZjYtNWE5NWU4NzU5YWExIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDc3NzQwNjksImV4cCI6MTcwNzc3NDk2OX0.VDt8BYfkkKSnVKU73WTEg-54G10FtRia9bInR4YpMp0

{
    "learned_artwork_ids": [],
    "experience_points": 0
}