###
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "username": "roni",
    "password": "123",
    "firstName": "roni",
    "lastName": "gotlib",
    "gender": "Female"
}


###
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username": "roni",
    "password": "123"
}


###
POST http://localhost:5000/api/user/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwOTIxMjcxMiwianRpIjoiNzg1NjU3NTEtODNlYi00OTM3LWJmMTktZjEzYmYxODA3ZDA3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDkyMTI3MTIsImV4cCI6MTcwOTIxNjMxMn0._ctIO1FIDiPrwZi-sDfJHFLOLs4AQm2CqIQHbsIB1og

###
POST http://localhost:5000/api/user/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzA4MTI1MCwianRpIjoiZjE2NmVmNTgtNjZiNS00ZGQ0LWFhMmUtYjczYzQ3ZjZjYzkyIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InVzZXIiLCJuYmYiOjE3MDcwODEyNTAsImV4cCI6MTcwNzA4MjE1MH0.lOHUEwETaiTIaCq1RD5LDHigrqPa11HfoTAyssvT3E8

###
GET http://localhost:5000/api/user/scores
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzA4NDQ3MiwianRpIjoiNDI2YWM2ODUtMmZjYy00YzhlLTlmN2YtNTdhYWYwYThiYWZhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDcwODQ0NzIsImV4cCI6MTcwNzA4NTM3Mn0.CDlOyiLwZzae54ZC3xN_Ei-jVySC6EurP6AZoURqI2E

###
GET http://localhost:5000/api/user/above_average
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwNzc3NTExMywianRpIjoiODg5Y2EyMDYtMTgwYi00ZDdmLTllMWQtZDdlYWExNmQ4NDBmIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDc3NzUxMTMsImV4cCI6MTcwNzc3ODcxM30.FCiPk4SafzzK-N4HYNHXqy1QAmvM7qZX2fi3K4djrm4

###
GET http://localhost:5000/api/artworks/all_learned
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwOTIyNzEwMywianRpIjoiZjEwOGVmYmYtZjMyOS00MWUzLTk1MWQtNTkyMzI3MzFhMDc2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDkyMjcxMDMsImV4cCI6MTcwOTIzMDcwM30.y251ZtXZAsaWM3Zvri4dwYAwtjg401CUPW3pdOvZeag

###
GET http://localhost:5000/api/artworks/learned
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwOTIxMjcxMiwianRpIjoiNzg1NjU3NTEtODNlYi00OTM3LWJmMTktZjEzYmYxODA3ZDA3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDkyMTI3MTIsImV4cCI6MTcwOTIxNjMxMn0._ctIO1FIDiPrwZi-sDfJHFLOLs4AQm2CqIQHbsIB1og
###
GET http://localhost:5000/api/artworks/filters
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwOTIyNzEwMywianRpIjoiZjEwOGVmYmYtZjMyOS00MWUzLTk1MWQtNTkyMzI3MzFhMDc2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDkyMjcxMDMsImV4cCI6MTcwOTIzMDcwM30.y251ZtXZAsaWM3Zvri4dwYAwtjg401CUPW3pdOvZeag

###
POST http://localhost:5000/api/artworks/filter_results
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwOTIzMjEwMywianRpIjoiOTI0MTdjY2MtMjI3YS00ZjQ3LWI2MzctNGQwYWJkYzcxMzcwIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDkyMzIxMDMsImV4cCI6MTcwOTIzNTcwM30.EjDwQAST9csh-Qrm025UwbzQb1YNBMyx6EopHot-XhM

{
    "artist_names": [],
    "artist_nationalities": [],
    "artwork_culture": [],
    "artwork_classification": [],
    "gender": [],
    "dimensions":[],
    "time_range": {"minYear": 0, "maxYear": 1670},
    "get_oldest_artworks": true
}

###
POST http://localhost:5000/api/artworks/update_test_results
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcwOTIxMjcxMiwianRpIjoiNzg1NjU3NTEtODNlYi00OTM3LWJmMTktZjEzYmYxODA3ZDA3IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InJvbmkiLCJuYmYiOjE3MDkyMTI3MTIsImV4cCI6MTcwOTIxNjMxMn0._ctIO1FIDiPrwZi-sDfJHFLOLs4AQm2CqIQHbsIB1og

{
    "learned_artwork_ids": [],
    "experience_points": 0
}